name: Deployment

# on commit push, run job
on: [ push ]

jobs:
  run:
    # worker runs on latest ubuntu
    runs-on: ubuntu-latest

    steps:
      # checkout to our repository so we have access to the source code
      - uses: actions/checkout@v3

      # the actual deployment to google
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
          create_credentials_file: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Verify Authentication
        run: |
          gcloud auth list
          gcloud config list project
          
      - name: Set GCP Project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          echo "Current project is $(gcloud config get-value project)"

      - name: Deploy Cloud Function
        id: deploy
        run: |
          gcloud functions deploy vectorizer \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --entry-point hello_world \
          --region=us-central1 \
          --gen2 \
          --source ./src

      - name: Verify Deployment
        if: success()
        run: |
          gcloud functions describe vectorizer \
            --gen2 \
            --region=us-central1
