name: Deployment

# on commit push, run job
on: [ push ]

jobs:
  run:
    # worker runs on latest ubuntu
    runs-on: ubuntu-latest

    steps:
      # checkout to our repository so we have access to the source code
      - uses: actions/checkout@v2

      # the actual deployment to google
      - name: Cloud Functions Deploy
        uses: google-github-actions/auth@v2
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          name: python-hello-world-cf
          description: Test python cloud function # nullable
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          region: europe-west1
          source_dir: src
          # name of our function in our main.py file, defaults to the resource name suffix 
          entry_point: hello_world
          # runtime to use for the function
          runtime: python39
#       env_vars: # optional
